name: Backend Build With Maven

on: push

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Validate commit title
        shell: bash
        run: |
          message=$(git log -1 --format=%s)
          pattern='^(feat|chore|refactor|fix|perf|docs)(\([^()[:space:]]+\))?: [^[:space:]].*$'

          if [[ ! "$message" =~ $pattern ]]; then
            echo "Invalid commit title."
            echo "Expected: <type>: <message> or <type>(<scope>): <message>"
            echo "Allowed types: feat, chore, refactor, fix, perf, docs"
            exit 1
          fi
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn -B package --file pom.xml

      # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
      - name: Update dependency graph
        uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
